import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { FIELDS, duplicateReason, haversineMeters, keySets, normalizeAddress, normalizeName } from "./core.mjs";

const root = process.cwd(), output = path.join(root, "data/location-backfill");
function parseCsv(source) { const records = []; let record = [], field = "", quoted = false; for (let i = 0; i < source.length; i++) { const c = source[i]; if (quoted && c === '"' && source[i + 1] === '"') { field += '"'; i++; } else if (c === '"') quoted = !quoted; else if (!quoted && c === ",") { record.push(field); field = ""; } else if (!quoted && c === "\n") { record.push(field); if (record.some(Boolean)) records.push(record); record = []; field = ""; } else if (c !== "\r") field += c; } if (field || record.length) { record.push(field); records.push(record); } const [headers, ...rows] = records; return rows.map((values) => Object.fromEntries(headers.map((header, i) => [header, values[i] ?? ""]))); }
const rows = parseCsv(await readFile(path.join(output, "location-candidates.csv"), "utf8")), existing = JSON.parse(await readFile(path.join(output, "existing-locations.json"), "utf8")), generation = JSON.parse(await readFile(path.join(output, "report.json"), "utf8"));
const currentColumns = JSON.parse(await readFile(path.join(output, "locations-columns.json"), "utf8")), migration = await readFile(path.join(root, "supabase/migrations/20260722_location_backfill_metadata.sql"), "utf8"), sql = await readFile(path.join(root, "supabase/seeds/20260722_location_backfill_candidates.sql"), "utf8");
const migrationColumns = [...migration.matchAll(/add column if not exists\s+(\w+)/gi)].map((m) => m[1]), availableColumns = new Set([...currentColumns, ...migrationColumns]);
const by = (field) => Object.fromEntries(Object.entries(rows.reduce((acc, row) => { const key = row[field] || "(空欄)"; acc[key] = (acc[key] || 0) + 1; return acc; }, {})).sort(([a], [b]) => a.localeCompare(b, "ja")));
const missing = Object.fromEntries(["name", "chain_name", "category", "prefecture", "city", "address", "latitude", "longitude", "coordinate_source", "coordinate_checked_at", "official_store_id", "official_url", "source_name", "source_url", "source_checked_at", "verification_status"].map((field) => [field, rows.filter((row) => !String(row[field] ?? "").trim()).length]));
const domains = { "バンダイ ガシャポンどこ?": ["gashapon.jp"], "gashacoco公式ショップリスト": ["gashacoco.jp"], "ヤマダデンキ公式店舗一覧": ["www.yamada-denki.jp"] }, domainErrors = [], invalidStatuses = [], invalidCandidateClaims = [], htmlFragments = [], blankWhitespace = [];
const candidateSets = keySets(), duplicateCounts = { official_store_id: 0, official_url: 0, name_address: 0 }, existingSets = keySets(existing), existingDuplicateCounts = { official_store_id: 0, official_url: 0, name_address: 0 };
for (const row of rows) {
  try { if (!(domains[row.source_name] || []).includes(new URL(row.official_url).hostname)) domainErrors.push({ name: row.name, url: row.official_url }); } catch { domainErrors.push({ name: row.name, url: row.official_url }); }
  if (!["confirmed", "candidate"].includes(row.verification_status)) invalidStatuses.push(row.name);
  if (row.verification_status === "candidate" && !row.candidate_reason) invalidCandidateClaims.push(row.name);
  for (const field of FIELDS) { const value = String(row[field] ?? ""); if (/<[^>]+>|&(?:#\d+|#x[\da-f]+|[a-z]+);/i.test(value)) htmlFragments.push({ name: row.name, field }); if (value && !value.trim()) blankWhitespace.push({ name: row.name, field }); }
  const duplicate = duplicateReason(row, candidateSets); if (duplicate) duplicateCounts[duplicate]++; else { candidateSets.id.add(row.official_store_id); candidateSets.url.add(row.official_url.replace(/\/$/, "")); candidateSets.nameAddress.add(`${normalizeName(row.name)}\u0000${normalizeAddress(row.address)}`); }
  const existingDuplicate = duplicateReason(row, existingSets); if (existingDuplicate) existingDuplicateCounts[existingDuplicate]++;
}
const nearby = []; for (let i = 0; i < rows.length; i++) { const a = rows[i]; if (!a.latitude || !a.longitude) continue; const aa = { latitude: Number(a.latitude), longitude: Number(a.longitude) }; for (let j = i + 1; j < rows.length; j++) { const b = rows[j]; if (!b.latitude || !b.longitude || a.prefecture !== b.prefecture) continue; const distance = haversineMeters(aa, { latitude: Number(b.latitude), longitude: Number(b.longitude) }); if (distance <= 30) nearby.push({ distance_meters: Math.round(distance * 10) / 10, first: { name: a.name, address: a.address }, second: { name: b.name, address: b.address }, merged: false }); if (nearby.length >= 300) break; } if (nearby.length >= 300) break; }
const insert = sql.match(/insert into public\.locations\s*\(([^)]+)\)/i), insertColumns = insert ? insert[1].split(",").map((v) => v.trim()) : [];
const sqlAudit = { candidate_rows: (sql.match(/^\s*\('/gm) || []).length, insert_columns: insertColumns, unknown_after_migration: insertColumns.filter((column) => !availableColumns.has(column)), has_not_exists: /where not exists/i.test(sql), has_on_conflict: /on conflict do nothing/i.test(sql), updates_locations: /update\s+public\.locations/i.test(sql), deletes_locations: /delete\s+from\s+public\.locations/i.test(sql), truncates_locations: /truncate\s+(?:table\s+)?public\.locations/i.test(sql) };
const audit = { audited_at: new Date().toISOString(), candidate_count: rows.length, projected_total: existing.length + rows.length, by_source: by("source_name"), by_chain: by("chain_name"), by_prefecture: by("prefecture"), by_verification: by("verification_status"), by_coordinate_source: by("coordinate_source"), missing, coordinate_improvement: generation.coordinate_improvement, collection_errors: generation.sources.reduce((sum, source) => sum + source.errors, 0), official_domain_errors: domainErrors, invalid_statuses: invalidStatuses, candidate_without_reason: invalidCandidateClaims, html_fragments: htmlFragments, whitespace_only: blankWhitespace, candidate_duplicates: duplicateCounts, existing_duplicates: existingDuplicateCounts, nearby_duplicates: nearby, sql: sqlAudit, prefecture_samples: generation.prefecture_samples, samples: generation.samples };
await writeFile(path.join(output, "audit-report.json"), `${JSON.stringify(audit, null, 2)}\n`);
const table = (obj) => Object.entries(obj).map(([key, value]) => `| ${key} | ${value} |`).join("\n"), sampleText = Object.entries(audit.samples).map(([chain, list]) => `### ${chain}\n\n${list.slice(0, 10).map((row, i) => `${i + 1}. ${row.name} / ${row.prefecture}${row.city} / ${row.verification_status} / ${row.official_url}`).join("\n")}`).join("\n\n");
await writeFile(path.join(output, "AUDIT_REPORT.md"), `# 公式店舗バックフィル監査レポート\n\n監査日時: ${audit.audited_at}\n\n- 候補: ${rows.length}\n- 合計見込み: ${audit.projected_total}\n- confirmed: ${audit.by_verification.confirmed || 0}\n- candidate: ${audit.by_verification.candidate || 0}\n- 既存重複: ${Object.values(existingDuplicateCounts).reduce((a, b) => a + b, 0)}\n- 候補内重複: ${Object.values(duplicateCounts).reduce((a, b) => a + b, 0)}\n- 30m以内の近接候補: ${nearby.length}（別テナントを考慮して自動統合なし）\n- 公式ドメイン不一致: ${domainErrors.length}\n- HTML断片: ${htmlFragments.length}\n- 空白だけの項目: ${blankWhitespace.length}\n- 収集エラー: ${audit.collection_errors}\n\n## 情報元別\n\n| 情報元 | 件数 |\n|---|---:|\n${table(audit.by_source)}\n\n## 確認状態別\n\n| 状態 | 件数 |\n|---|---:|\n${table(audit.by_verification)}\n\n## 都道府県別\n\n| 都道府県 | 件数 |\n|---|---:|\n${table(audit.by_prefecture)}\n\n## 欠損\n\n| 項目 | 件数 |\n|---|---:|\n${table(missing)}\n\n## 代表サンプル\n\n${sampleText}\n\n## 近接重複候補\n\n全件は \`audit-report.json\` の \`nearby_duplicates\` に記録しています。近接していても同一施設内の別テナントは統合していません。\n`);
console.log(JSON.stringify({ candidates: rows.length, projected: audit.projected_total, verification: audit.by_verification, missing, domain_errors: domainErrors.length, candidate_duplicates: duplicateCounts, existing_duplicates: existingDuplicateCounts, nearby: nearby.length, sql: sqlAudit, errors: audit.collection_errors }, null, 2));
